.TH "DirectoryStructure" 3 "Fri Nov 5 2021" "Version 1.0" "FUSE_myFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectoryStructure
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <myFS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumFiles\fP"
.br
.ti -1c
.RI "\fBFileStruct\fP \fBfiles\fP [\fBMAX_FILES_PER_DIRECTORY\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBFileStruct\fP files[\fBMAX_FILES_PER_DIRECTORY\fP]"

.SS "int numFiles"


.SH "Author"
.PP 
Generated automatically by Doxygen for FUSE_myFS from the source code\&.
