.TH "SuperBlockStructure" 3 "Fri Nov 5 2021" "Version 1.0" "FUSE_myFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuperBlockStructure
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <myFS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "time_t \fBcreationTime\fP"
.br
.ti -1c
.RI "int \fBdiskSizeInBlocks\fP"
.br
.ti -1c
.RI "int \fBnumOfFreeBlocks\fP"
.br
.ti -1c
.RI "int \fBblockSize\fP"
.br
.ti -1c
.RI "int \fBmaxLenFileName\fP"
.br
.ti -1c
.RI "int \fBmaxBlocksPerFile\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int blockSize"

.SS "time_t creationTime"

.SS "int diskSizeInBlocks"

.SS "int maxBlocksPerFile"

.SS "int maxLenFileName"

.SS "int numOfFreeBlocks"


.SH "Author"
.PP 
Generated automatically by Doxygen for FUSE_myFS from the source code\&.
